### ISSUE TITLE
Question about ricoh theta s camera using ptp-ip

### ISSUE THREAD

**Issue by Nick-0814** [theta360developers/ricoh-viewer#17]
Hi，Craig, I'm sorry to bother you.

I am a rookie in the direction of robot SLAM. I was recently researching panoramic cameras (ricoh theta  s), and saw that your research on this camera on github is quite in-depth. So I would like to ask you, can this camera be triggered using ptp-ip control?

Best regards,
Nick

**Comment by codetricity** [comment]
Nick, sorry for the late response, I did not see this question until just now.  We have an active community here:
https://community.theta360.guide/

Can you put your question in the .guide forum above?

The THETA S can use PTP (MTP) protocol over a USB cable.  

TCP/IP will not work over the USB cable.   To use TCP/IP, you can use WiFi.  However, the WiFi will only be able to stream in motionjpeg

You can get more information here:

https://community.theta360.guide/t/live-streaming-over-usb-on-ubuntu-and-linux-nvidia-jetson/4359?u=craig

There is a ROS package for the THETA S that may be of use to you:

https://github.com/RobInLabUJI/ricoh_camera

https://github.com/johnny04thomas/rgbd_stereo_360camera
